### ISSUE TITLE
home navigation is not taking request (problem in base.html)

### ISSUE THREAD

**Issue by lokesh576** [chdinesh1089/cts#10]
`{% if request.user.is_admin %}
      <a class="active" href="{% url 'admin_complaints_view' %}"><i class="fa fa-fw fa-home"></i> Home</a>
      <p>Welcome Admin!!</p>
      {% else %}
      <a href="{% url 'user_complaints_view' %}" class="{{ home_header }}"><i class="fa fa-fw fa-home"></i> Home</a>
        <p>Welcome {{ user_name }}!!</p>
      {% endif %}`

**Comment by chdinesh1089** [comment]
should be user.profile.is_admin. you cang change it
